name: Pull Request Ci
on:
    pull_request

jobs:
    pull_request_ci:
        name: Pull Request Ci
        runs-on: ubuntu-latest
        steps:
            - name: Echo Hello world
              run: |
               echo "Hello World"
            - name: Print Github details
              run: |
               echo  "sha" = $GITHUB_SHA
               echo  "ref" = ${{github.ref}}
               echo  "pr request id " = ${{github.event.before}}
               


             